import type { MenuItem } from "@/types"

export const menuItems: MenuItem[] = [
  // Burger King
  {
    id: "m1",
    restaurantId: "r1",
    name: "Whopper",
    description:
      "Flame-grilled beef patty topped with tomatoes, lettuce, mayo, ketchup, pickles, and onions on a sesame seed bun.",
    price: 5.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Burgers",
    popular: true,
  },
  {
    id: "m2",
    restaurantId: "r1",
    name: "Chicken Fries",
    description: "Chicken strips shaped like fries, perfect for dipping.",
    price: 3.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Chicken",
  },
  {
    id: "m3",
    restaurantId: "r1",
    name: "Onion Rings",
    description: "Crispy, golden onion rings.",
    price: 2.49,
    image: "/placeholder.svg?height=100&width=100",
    category: "Sides",
  },
  {
    id: "m4",
    restaurantId: "r1",
    name: "Chocolate Shake",
    description: "Creamy chocolate milkshake topped with whipped cream.",
    price: 3.29,
    image: "/placeholder.svg?height=100&width=100",
    category: "Drinks",
  },

  // Pizza Hut
  {
    id: "m5",
    restaurantId: "r2",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni pizza with mozzarella cheese and tomato sauce.",
    price: 12.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Pizzas",
    popular: true,
  },
  {
    id: "m6",
    restaurantId: "r2",
    name: "Cheese Breadsticks",
    description: "Warm breadsticks topped with melted cheese and served with marinara sauce.",
    price: 6.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Sides",
  },
  {
    id: "m7",
    restaurantId: "r2",
    name: "Buffalo Wings",
    description: "Spicy buffalo wings served with ranch dressing.",
    price: 8.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Wings",
    popular: true,
  },
  {
    id: "m8",
    restaurantId: "r2",
    name: "Veggie Supreme Pizza",
    description: "Pizza topped with bell peppers, onions, mushrooms, olives, and tomatoes.",
    price: 14.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Pizzas",
  },

  // Taco Bell
  {
    id: "m9",
    restaurantId: "r3",
    name: "Crunchy Taco",
    description: "Crispy corn shell filled with seasoned beef, lettuce, and cheese.",
    price: 1.79,
    image: "/placeholder.svg?height=100&width=100",
    category: "Tacos",
    popular: true,
  },
  {
    id: "m10",
    restaurantId: "r3",
    name: "Burrito Supreme",
    description: "Flour tortilla filled with beef, beans, sour cream, lettuce, tomatoes, and cheese.",
    price: 4.29,
    image: "/placeholder.svg?height=100&width=100",
    category: "Burritos",
    popular: true,
  },
  {
    id: "m11",
    restaurantId: "r3",
    name: "Nachos BellGrande",
    description: "Crispy nachos topped with beef, beans, sour cream, tomatoes, and cheese.",
    price: 5.49,
    image: "/placeholder.svg?height=100&width=100",
    category: "Nachos",
  },
  {
    id: "m12",
    restaurantId: "r3",
    name: "Quesadilla",
    description: "Grilled flour tortilla filled with cheese and chicken.",
    price: 3.99,
    image: "/placeholder.svg?height=100&width=100",
    category: "Quesadillas",
  },
]

